name: close stale
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.PAT }}
          any-of-labels: 'rejected','dropped'
          stale-issue-label: 'stale'
          days-before-stale: 2
          days-before-close: 1
